#!/bin/bash
# qsub script to submit to nyu's scheduler
# submit with: qsub -l nodes=1:ppn=3,mem=24GB,walltime=48:00:00 /home/mss460/coversongs-tensorflow/process_audiodata_qsub

module load python/gnu/3.4.4
python /home/mss460/coversongs-tensorflow/process_audiodata.py
