#!/bin/bash
# qsub script to submit to nyu's scheduler
# submit with: qsub -l nodes=1:ppn=3,mem=24GB,walltime=48:00:00 /home/mss460/coversongs-tensorflow/process_audiodata_qsub

module load python3/intel/3.5.1
python3 /home/mss460/coversongs-tensorflow/process_audiodata.py
